[feat] multiKeyword complete
KeywordHanaro/KeywordHanaro_FE pull request #121
Opened 2024-11-27 06:36 UTC by 99andrew99

2024-11-29 00:11 UTC, ezenjun requested changes

2024-11-29 00:11 UTC, ezenjun commented on components/templates/multiKeyword/MultiKeywordComponent.tsx
파일명이 완료, 결과 등의 느낌이 나지 않는 것 같습니다. 조금 더 직관적으로 수정해주세요

2024-11-29 00:11 UTC, ezenjun commented on components/templates/multiKeyword/MultiKeywordComponent.tsx
> +      {isMultiTransfer(data) && (
div 안에서 type에 따라 렌더링하는 것 보다 type에 따라서 return 하는 방식이 나을 것 같습니다.

2024-12-13 02:20 UTC, 99andrew99 commented
SettlementCompletion의 메세지를 대체 했습니다.
TransferCompletion의 메세지는 TransferAmountKeyword 타입의 BaseKeyword 타입에 id, title 형식이 필요해서 불가능하다고 판단했습니다.

2024-12-13 09:03 UTC, merged